// packages/react/src/components/Calendar/DatePicker.tsx
/**
 * @usevyre/react — DatePicker
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────────┐
 * │ Component:  DatePicker (input trigger + popover Calendar)   │
 * │ Import:     import { DatePicker } from "@usevyre/react"     │
 * │                                                             │
 * │ = all Calendar props +                                       │
 * │   placeholder    = string (default "Pick a date")           │
 * │   inputClassName = string                                    │
 * │                                                             │
 * │ mode = "single"(default) | "range" | "multiple"             │
 * │ value = Date | [Date,Date] | Date[] (matches mode)          │
 * │                                                             │
 * │ Renders a button that opens a Calendar in a portal popover. │
 * │ For an always-visible inline grid, use Calendar.            │
 * │ For start/end ranges with presets + dual month, use         │
 * │ DateRangePicker.                                            │
 * └─────────────────────────────────────────────────────────────┘
 *
 * @example
 * // Single date
 * <DatePicker mode="single" value={date} onChange={setDate} placeholder="Pick a date" />
 *
 * // Date + time
 * <DatePicker value={date} onChange={setDate} showTime />
 */

import React, {
  useCallback, useEffect, useMemo, useRef, useState,
} from "react";
import ReactDOM from "react-dom";
import { cn } from "../../utils/cn";
import {
  Calendar,
  formatDate,
  formatTime,
  type CalendarProps,
  type CalendarSingleProps,
  type CalendarRangeProps,
  type CalendarMultipleProps,
  type CalendarBaseProps,
  type DatePickerProps,
} from "./Calendar";

export type { DatePickerProps };

function formatPickerValue(props: CalendarProps): string {
  if (props.mode === "range") {
    const [s, e] = props.value ?? [null, null];
    if (!s) return "";
    if (!e) return formatDate(s);
    return `${formatDate(s)} – ${formatDate(e)}`;
  }
  if (props.mode === "multiple") {
    const dates = props.value ?? [];
    if (dates.length === 0) return "";
    if (dates.length === 1) return formatDate(dates[0]);
    return `${dates.length} dates selected`;
  }
  const v = (props as CalendarSingleProps).value;
  const showTime = (props as CalendarBaseProps).showTime;
  if (!v) return "";
  return showTime ? `${formatDate(v)} ${formatTime(v)}` : formatDate(v);
}

export const DatePicker = React.forwardRef<HTMLDivElement, DatePickerProps>(
  ({ placeholder = "Pick a date", inputClassName, ...calendarProps }, ref) => {
    const [open, setOpen] = useState(false);
    const triggerRef = useRef<HTMLButtonElement>(null);
    const popoverRef = useRef<HTMLDivElement>(null);
    const [pos, setPos] = useState({ top: 0, left: 0, width: 0 });

    const displayValue = formatPickerValue(calendarProps);

    const updatePos = useCallback(() => {
      if (!triggerRef.current) return;
      const rect = triggerRef.current.getBoundingClientRect();
      setPos({
        top: rect.bottom + window.scrollY + 6,
        left: rect.left + window.scrollX,
        width: rect.width,
      });
    }, []);

    useEffect(() => {
      if (!open) return;
      updatePos();
      const onScroll = () => updatePos();
      const onResize = () => updatePos();
      window.addEventListener("scroll", onScroll, true);
      window.addEventListener("resize", onResize);
      return () => {
        window.removeEventListener("scroll", onScroll, true);
        window.removeEventListener("resize", onResize);
      };
    }, [open, updatePos]);

    useEffect(() => {
      if (!open) return;
      const onPointerDown = (e: PointerEvent) => {
        if (
          !popoverRef.current?.contains(e.target as Node) &&
          !triggerRef.current?.contains(e.target as Node)
        ) {
          setOpen(false);
        }
      };
      const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); };
      document.addEventListener("pointerdown", onPointerDown);
      document.addEventListener("keydown", onKey);
      return () => {
        document.removeEventListener("pointerdown", onPointerDown);
        document.removeEventListener("keydown", onKey);
      };
    }, [open]);

    const autoClose = calendarProps.mode !== "range" && calendarProps.mode !== "multiple" && !calendarProps.showTime;

    const wrappedProps: CalendarProps = useMemo(() => {
      if (calendarProps.mode === "range") {
        return {
          ...calendarProps,
          onChange: (v: [Date | null, Date | null]) => {
            (calendarProps as CalendarRangeProps).onChange?.(v);
            if (v[0] && v[1]) setOpen(false);
          },
        };
      }
      if (calendarProps.mode === "multiple") return calendarProps;
      return {
        ...calendarProps,
        onChange: (v) => {
          (calendarProps as CalendarSingleProps).onChange?.(v);
          if (autoClose) setOpen(false);
        },
      };
    }, [calendarProps, autoClose]);

    return (
      <div ref={ref} className="vyre-datepicker">
        <button
          ref={triggerRef}
          type="button"
          className={cn("vyre-datepicker__trigger", !displayValue && "vyre-datepicker__trigger--placeholder", inputClassName)}
          onClick={() => { updatePos(); setOpen((o) => !o); }}
          aria-expanded={open}
          aria-haspopup="dialog"
        >
          <svg className="vyre-datepicker__icon" width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
            <rect x="1.5" y="2.5" width="11" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.3"/>
            <path d="M1.5 6h11M4.5 1v3M9.5 1v3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
          </svg>
          <span>{displayValue || placeholder}</span>
          {displayValue && (
            <button
              className="vyre-datepicker__clear"
              type="button"
              aria-label="Clear"
              onClick={(e) => {
                e.stopPropagation();
                if (calendarProps.mode === "range") (calendarProps as CalendarRangeProps).onChange?.([null, null]);
                else if (calendarProps.mode === "multiple") (calendarProps as CalendarMultipleProps).onChange?.([]);
                else (calendarProps as CalendarSingleProps).onChange?.(null);
              }}
            >
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                <path d="M2 2l8 8M10 2l-8 8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
              </svg>
            </button>
          )}
        </button>

        {open && ReactDOM.createPortal(
          <div
            ref={popoverRef}
            className="vyre-datepicker__popover"
            role="dialog"
            aria-label="Date picker"
            style={{ top: pos.top, left: pos.left, minWidth: pos.width }}
          >
            <Calendar {...wrappedProps} />
          </div>,
          document.body
        )}
      </div>
    );
  }
);
DatePicker.displayName = "VyreDatePicker";

// packages/vue/src/components/Calendar/DatePicker.vue
<script setup lang="ts">
/**
 * @usevyre/vue — DatePicker
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────────┐
 * │ Component:  DatePicker (input trigger + popover Calendar)   │
 * │ Import:     import { DatePicker } from "@usevyre/vue"       │
 * │                                                             │
 * │ = all Calendar props +                                       │
 * │   placeholder = string (default "Pick a date")              │
 * │   inputClass  = string                                       │
 * │                                                             │
 * │ mode = "single"(default) | "range" | "multiple"             │
 * │ modelValue = Date | [Date,Date] | Date[] (matches mode)     │
 * │ Events: @update:modelValue                                  │
 * │                                                             │
 * │ For an always-visible inline grid, use Calendar.            │
 * │ For start/end ranges with presets, use DateRangePicker.     │
 * └─────────────────────────────────────────────────────────────┘
 *
 * @example
 * <DatePicker v-model="date" placeholder="Pick a date" />
 * <DatePicker mode="range" v-model="range" />
 */

import { computed, onMounted, onUnmounted, ref } from "vue";
import { cn } from "../../utils/cn";
import Calendar from "./Calendar.vue";

type CalendarMode = "single" | "range" | "multiple";

const props = withDefaults(defineProps<{
  mode?: CalendarMode;
  modelValue?: Date | null | [Date | null, Date | null] | Date[];
  showTime?: boolean;
  minDate?: Date;
  maxDate?: Date;
  disabled?: (date: Date) => boolean;
  weekStartsOn?: 0 | 1;
  placeholder?: string;
  inputClass?: string;
  class?: string;
}>(), {
  mode: "single",
  showTime: false,
  weekStartsOn: 1,
  placeholder: "Pick a date",
});

const emit = defineEmits<{
  (e: "update:modelValue", v: Date | null | [Date | null, Date | null] | Date[]): void;
}>();

const open = ref(false);
const triggerRef = ref<HTMLElement | null>(null);
const popoverRef = ref<HTMLElement | null>(null);
const popoverPos = ref({ top: 0, left: 0 });

function updatePos() {
  if (!triggerRef.value) return;
  const rect = triggerRef.value.getBoundingClientRect();
  popoverPos.value = {
    top: rect.bottom + window.scrollY + 6,
    left: rect.left + window.scrollX,
  };
}

function handleToggle() {
  updatePos();
  open.value = !open.value;
}

function onPointerDown(e: PointerEvent) {
  if (!popoverRef.value?.contains(e.target as Node) && !triggerRef.value?.contains(e.target as Node)) {
    open.value = false;
  }
}
function onKey(e: KeyboardEvent) {
  if (e.key === "Escape") open.value = false;
}

onMounted(() => {
  document.addEventListener("pointerdown", onPointerDown);
  document.addEventListener("keydown", onKey);
});
onUnmounted(() => {
  document.removeEventListener("pointerdown", onPointerDown);
  document.removeEventListener("keydown", onKey);
});

// ── Display value ─────────────────────────────────────────────

function formatDate(d: Date | null): string {
  if (!d) return "";
  return new Intl.DateTimeFormat("default", { year: "numeric", month: "short", day: "numeric" }).format(d);
}
function formatTime(d: Date): string {
  return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

const displayValue = computed(() => {
  if (props.mode === "range") {
    const [s, e] = (props.modelValue as [Date|null,Date|null]) ?? [null, null];
    if (!s) return "";
    if (!e) return formatDate(s);
    return `${formatDate(s)} – ${formatDate(e)}`;
  }
  if (props.mode === "multiple") {
    const dates = (props.modelValue as Date[]) ?? [];
    if (dates.length === 0) return "";
    if (dates.length === 1) return formatDate(dates[0]);
    return `${dates.length} dates selected`;
  }
  const v = props.modelValue as Date | null;
  if (!v) return "";
  return props.showTime ? `${formatDate(v)} ${formatTime(v)}` : formatDate(v);
});

function handleChange(v: Date | null | [Date | null, Date | null] | Date[]) {
  emit("update:modelValue", v);
  // Auto-close for single (no time) and range when both dates selected
  if (props.mode === "single" && !props.showTime) {
    open.value = false;
  } else if (props.mode === "range") {
    const [, e] = v as [Date|null,Date|null];
    if (e) open.value = false;
  }
}

function handleClear(e: MouseEvent) {
  e.stopPropagation();
  if (props.mode === "range") emit("update:modelValue", [null, null]);
  else if (props.mode === "multiple") emit("update:modelValue", []);
  else emit("update:modelValue", null);
}
</script>

<template>
  <div :class="cn('vyre-datepicker', props.class)">
    <button
      ref="triggerRef"
      type="button"
      :class="cn('vyre-datepicker__trigger', !displayValue && 'vyre-datepicker__trigger--placeholder', props.inputClass)"
      :aria-expanded="open"
      aria-haspopup="dialog"
      @click="handleToggle"
    >
      <svg class="vyre-datepicker__icon" width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
        <rect x="1.5" y="2.5" width="11" height="10" rx="1.5" stroke="currentColor" stroke-width="1.3"/>
        <path d="M1.5 6h11M4.5 1v3M9.5 1v3" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>
      </svg>
      <span>{{ displayValue || placeholder }}</span>
      <button
        v-if="displayValue"
        class="vyre-datepicker__clear"
        type="button"
        aria-label="Clear"
        @click="handleClear"
      >
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
          <path d="M2 2l8 8M10 2l-8 8" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/>
        </svg>
      </button>
    </button>

    <Teleport to="body">
      <div
        v-if="open"
        ref="popoverRef"
        class="vyre-datepicker__popover"
        role="dialog"
        aria-label="Date picker"
        :style="{ top: `${popoverPos.top}px`, left: `${popoverPos.left}px` }"
      >
        <Calendar
          :mode="mode"
          :model-value="modelValue"
          :show-time="showTime"
          :min-date="minDate"
          :max-date="maxDate"
          :disabled="disabled"
          :week-starts-on="weekStartsOn"
          @update:model-value="handleChange"
        />
      </div>
    </Teleport>
  </div>
</template>
