// packages/react/src/components/Checkbox/Checkbox.tsx
/**
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────┐
 * │ Component:  Checkbox                        │
 * │ checked      = boolean                      │
 * │ defaultChecked = boolean                    │
 * │ indeterminate  = boolean                    │
 * │ onCheckedChange = (checked: boolean) => void│
 * │ disabled     = boolean                      │
 * │ size         = "sm"|"md"(default)           │
 * │ CSS class:  .vyre-checkbox                  │
 * └─────────────────────────────────────────────┘
 */

import React from "react";

export interface CheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange" | "size"> {
  checked?: boolean;
  defaultChecked?: boolean;
  indeterminate?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  size?: "sm" | "md";
}

export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  (
    {
      checked: controlledChecked,
      defaultChecked,
      indeterminate = false,
      onCheckedChange,
      disabled,
      size = "md",
      className,
      id,
      ...props
    },
    ref
  ) => {
    const internalRef = React.useRef<HTMLInputElement>(null);
    const resolvedRef = (ref as React.RefObject<HTMLInputElement>) ?? internalRef;

    React.useEffect(() => {
      if (resolvedRef.current) {
        resolvedRef.current.indeterminate = indeterminate;
      }
    }, [indeterminate, resolvedRef]);

    return (
      <span
        className={["vyre-checkbox", `vyre-checkbox--${size}`, className].filter(Boolean).join(" ")}
        data-disabled={disabled || undefined}
        data-checked={controlledChecked || undefined}
        data-indeterminate={indeterminate || undefined}
      >
        <input
          ref={resolvedRef}
          type="checkbox"
          id={id}
          checked={controlledChecked}
          defaultChecked={defaultChecked}
          disabled={disabled}
          className="vyre-checkbox__input"
          onChange={(e) => onCheckedChange?.(e.target.checked)}
          {...props}
        />
        <span className="vyre-checkbox__box" aria-hidden="true">
          {indeterminate ? (
            <svg width="10" height="2" viewBox="0 0 10 2" fill="none">
              <path d="M1 1h8" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
            </svg>
          ) : (
            <svg width="10" height="8" viewBox="0 0 10 8" fill="none">
              <path d="M1 4l3 3 5-6" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          )}
        </span>
      </span>
    );
  }
);
Checkbox.displayName = "Checkbox";

// packages/vue/src/components/Checkbox/Checkbox.vue
<script setup lang="ts">
import { ref, watch } from "vue";

const props = withDefaults(defineProps<{
  modelValue?: boolean;
  defaultChecked?: boolean;
  indeterminate?: boolean;
  disabled?: boolean;
  size?: "sm" | "md";
  id?: string;
  class?: string;
}>(), { size: "md" });

const emit = defineEmits<{ "update:modelValue": [v: boolean] }>();

const inputRef = ref<HTMLInputElement | null>(null);

watch(() => props.indeterminate, (val) => {
  if (inputRef.value) inputRef.value.indeterminate = !!val;
}, { immediate: true });
</script>

<template>
  <span
    :class="['vyre-checkbox', `vyre-checkbox--${size}`, $props.class]"
    :data-disabled="disabled || undefined"
    :data-checked="modelValue || undefined"
    :data-indeterminate="indeterminate || undefined"
  >
    <input
      ref="inputRef"
      type="checkbox"
      :id="id"
      :checked="modelValue"
      :defaultChecked="defaultChecked"
      :disabled="disabled"
      class="vyre-checkbox__input"
      @change="(e) => emit('update:modelValue', (e.target as HTMLInputElement).checked)"
    />
    <span class="vyre-checkbox__box" aria-hidden="true">
      <svg v-if="indeterminate" width="10" height="2" viewBox="0 0 10 2" fill="none">
        <path d="M1 1h8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
      </svg>
      <svg v-else width="10" height="8" viewBox="0 0 10 8" fill="none">
        <path d="M1 4l3 3 5-6" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
  </span>
</template>
