// packages/vue/src/components/Switch/Switch.vue
<script setup lang="ts">
import { ref, computed } from "vue";

const props = withDefaults(defineProps<{
  modelValue?: boolean;
  defaultChecked?: boolean;
  disabled?: boolean;
  size?: "sm" | "md";
  class?: string;
}>(), { defaultChecked: false, size: "md" });

const emit = defineEmits<{ "update:modelValue": [v: boolean] }>();

const internal = ref(props.defaultChecked);
const isChecked = computed(() =>
  props.modelValue !== undefined ? props.modelValue : internal.value
);

function toggle() {
  if (props.disabled) return;
  const next = !isChecked.value;
  if (props.modelValue === undefined) internal.value = next;
  emit("update:modelValue", next);
}
</script>

<template>
  <button
    type="button"
    role="switch"
    :aria-checked="isChecked"
    :disabled="disabled"
    :data-checked="isChecked || undefined"
    :data-size="size"
    :class="['vyre-switch', $props.class]"
    @click="toggle"
  >
    <span class="vyre-switch__thumb" />
  </button>
</template>

// packages/react/src/components/Switch/Switch.tsx
/**
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────┐
 * │ Component:  Switch                          │
 * │ checked      = boolean                      │
 * │ defaultChecked = boolean                    │
 * │ onCheckedChange = (checked: boolean) => void│
 * │ disabled     = boolean                      │
 * │ size         = "sm"|"md"(default)           │
 * │ CSS class:  .vyre-switch                    │
 * └─────────────────────────────────────────────┘
 */

import React from "react";

export interface SwitchProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onChange"> {
  checked?: boolean;
  defaultChecked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
  disabled?: boolean;
  size?: "sm" | "md";
}

export const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  (
    {
      checked: controlledChecked,
      defaultChecked = false,
      onCheckedChange,
      disabled,
      size = "md",
      className,
      ...props
    },
    ref
  ) => {
    const [internalChecked, setInternalChecked] = React.useState(defaultChecked);
    const isChecked = controlledChecked !== undefined ? controlledChecked : internalChecked;

    const toggle = () => {
      if (disabled) return;
      const next = !isChecked;
      if (controlledChecked === undefined) setInternalChecked(next);
      onCheckedChange?.(next);
    };

    return (
      <button
        ref={ref}
        type="button"
        role="switch"
        aria-checked={isChecked}
        disabled={disabled}
        data-checked={isChecked || undefined}
        data-size={size}
        className={["vyre-switch", className].filter(Boolean).join(" ")}
        onClick={toggle}
        {...props}
      >
        <span className="vyre-switch__thumb" />
      </button>
    );
  }
);
Switch.displayName = "Switch";
