// packages/vue/src/components/NumberInput/NumberInput.vue
<!--
  @usevyre/vue — NumberInput

  AI CONTEXT:
  ┌──────────────────────────────────────────────────────────────────┐
  │ Component:  NumberInput                                           │
  │ Import:     import { NumberInput } from "@usevyre/vue"             │
  │                                                                   │
  │ Controlled numeric input with −/+ stepper. v-model is a NUMBER    │
  │ (or null when empty). Works inside <FormField> via its slot.      │
  │                                                                   │
  │   v-model       = number | null                                   │
  │   min max step  = number   (step default 1)                       │
  │   precision     = number   (decimal places)                       │
  │   size          = "sm" | "md"(default) | "lg"                     │
  │   disabled readonly = boolean                                     │
  │                                                                   │
  │ Clamps to min/max on blur. ArrowUp/Down ±step, Shift ±step×10.    │
  └──────────────────────────────────────────────────────────────────┘
-->
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { cn } from "../../utils/cn";

const props = withDefaults(
  defineProps<{
    modelValue?: number | null;
    defaultValue?: number | null;
    min?: number;
    max?: number;
    step?: number;
    precision?: number;
    size?: "sm" | "md" | "lg";
    disabled?: boolean;
    readonly?: boolean;
    class?: string;
  }>(),
  { step: 1, size: "md", disabled: false, readonly: false, defaultValue: null }
);

const emit = defineEmits<{ "update:modelValue": [v: number | null] }>();

const isControlled = computed(() => props.modelValue !== undefined);
const internal = ref<number | null>(props.defaultValue ?? null);
const value = computed<number | null>(() =>
  isControlled.value ? props.modelValue ?? null : internal.value
);

const clamp = (n: number) => {
  if (props.min !== undefined && n < props.min) return props.min;
  if (props.max !== undefined && n > props.max) return props.max;
  return n;
};
const round = (n: number) => {
  if (props.precision === undefined) return n;
  const f = 10 ** props.precision;
  return Math.round(n * f) / f;
};

const text = ref<string>(
  value.value === null || value.value === undefined ? "" : String(value.value)
);

watch(value, (v) => {
  const next = v === null || v === undefined ? "" : String(v);
  if (Number(text.value) !== v || text.value === "") text.value = next;
});

function commit(next: number | null) {
  if (!isControlled.value) internal.value = next;
  emit("update:modelValue", next);
}
function setNumber(n: number) {
  const v = round(clamp(n));
  text.value = String(v);
  commit(v);
}
function stepBy(dir: 1 | -1, multiplier = 1) {
  setNumber((value.value ?? 0) + dir * (props.step ?? 1) * multiplier);
}

function onInput(e: Event) {
  const raw = (e.target as HTMLInputElement).value;
  text.value = raw;
  if (raw === "" || raw === "-") {
    commit(null);
    return;
  }
  const n = Number(raw);
  if (!Number.isNaN(n)) commit(round(n));
}
function onBlur() {
  if (value.value !== null && value.value !== undefined) {
    const clamped = round(clamp(value.value));
    if (clamped !== value.value) setNumber(clamped);
    else text.value = String(clamped);
  } else {
    text.value = "";
  }
}
function onKeydown(e: KeyboardEvent) {
  if (props.disabled || props.readonly) return;
  if (e.key === "ArrowUp") {
    e.preventDefault();
    stepBy(1, e.shiftKey ? 10 : 1);
  } else if (e.key === "ArrowDown") {
    e.preventDefault();
    stepBy(-1, e.shiftKey ? 10 : 1);
  }
}

const atMin = computed(
  () => props.min !== undefined && value.value !== null && (value.value ?? 0) <= props.min
);
const atMax = computed(
  () => props.max !== undefined && value.value !== null && (value.value ?? 0) >= props.max
);

const classes = computed(() =>
  cn(
    "vyre-number-input",
    `vyre-number-input--${props.size}`,
    props.disabled && "vyre-number-input--disabled",
    props.class
  )
);
</script>

<template>
  <div :class="classes" :data-disabled="disabled ? '' : undefined">
    <button
      type="button"
      class="vyre-number-input__btn vyre-number-input__btn--dec"
      aria-label="Decrease"
      :tabindex="-1"
      :disabled="disabled || readonly || atMin"
      @click="stepBy(-1)"
    >
      <span aria-hidden="true">−</span>
    </button>
    <input
      type="text"
      inputmode="decimal"
      role="spinbutton"
      :aria-valuenow="value ?? undefined"
      :aria-valuemin="min"
      :aria-valuemax="max"
      class="vyre-number-input__field"
      :value="text"
      :disabled="disabled"
      :readonly="readonly"
      @input="onInput"
      @blur="onBlur"
      @keydown="onKeydown"
    />
    <button
      type="button"
      class="vyre-number-input__btn vyre-number-input__btn--inc"
      aria-label="Increase"
      :tabindex="-1"
      :disabled="disabled || readonly || atMax"
      @click="stepBy(1)"
    >
      <span aria-hidden="true">+</span>
    </button>
  </div>
</template>

// packages/react/src/components/NumberInput/NumberInput.tsx
/**
 * @usevyre/react — NumberInput
 *
 * AI CONTEXT:
 * ┌──────────────────────────────────────────────────────────────────┐
 * │ Component:  NumberInput                                           │
 * │ Import:     import { NumberInput } from "@usevyre/react"           │
 * │                                                                   │
 * │ Controlled numeric input with −/+ stepper buttons. onChange emits │
 * │ a NUMBER (or null when empty) — not an event. Drops straight into │
 * │ <FormField> (Form handles the non-event value automatically).     │
 * │                                                                   │
 * │   value     = number | null   (controlled)                        │
 * │   onChange  = (value: number | null) => void                      │
 * │   min max step = number   (step default 1)                        │
 * │   precision = number   (decimal places to round to)               │
 * │   size      = "sm" | "md"(default) | "lg"                         │
 * │   disabled readOnly = boolean                                     │
 * │                                                                   │
 * │ Clamps to min/max on blur. Keyboard: ArrowUp/Down ±step,          │
 * │ Shift+Arrow ±step×10. Empty input → null.                         │
 * └──────────────────────────────────────────────────────────────────┘
 *
 * @example
 * const [qty, setQty] = useState<number | null>(1);
 * <NumberInput value={qty} onChange={setQty} min={1} max={99} />
 *
 * @example
 * <FormField name="age" label="Age" rules={{ required: true, min: 18 }}>
 *   <NumberInput min={0} max={120} />
 * </FormField>
 */

import React from "react";
import { cn } from "../../utils/cn";
import type { Size, BaseProps } from "../../types";

export interface NumberInputProps
  extends Omit<
      React.InputHTMLAttributes<HTMLInputElement>,
      "size" | "value" | "onChange" | "defaultValue" | "type"
    >,
    BaseProps {
  /** Controlled value. null = empty. */
  value?: number | null;
  /** Uncontrolled initial value */
  defaultValue?: number | null;
  /** Called with the parsed number, or null when the field is empty */
  onChange?: (value: number | null) => void;
  min?: number;
  max?: number;
  /** Increment/decrement amount (default 1) */
  step?: number;
  /** Decimal places to round to */
  precision?: number;
  size?: Exclude<Size, "icon">;
  disabled?: boolean;
  readOnly?: boolean;
}

const clamp = (n: number, min?: number, max?: number) => {
  if (min !== undefined && n < min) return min;
  if (max !== undefined && n > max) return max;
  return n;
};

const round = (n: number, precision?: number) => {
  if (precision === undefined) return n;
  const f = 10 ** precision;
  return Math.round(n * f) / f;
};

export const NumberInput = React.forwardRef<HTMLInputElement, NumberInputProps>(
  (
    {
      value: controlledValue,
      defaultValue = null,
      onChange,
      min,
      max,
      step = 1,
      precision,
      size = "md",
      disabled = false,
      readOnly = false,
      className,
      onBlur,
      onKeyDown,
      ...rest
    },
    ref
  ) => {
    const isControlled = controlledValue !== undefined;
    const [internal, setInternal] = React.useState<number | null>(defaultValue);
    const value = isControlled ? controlledValue! : internal;

    // Raw text lets the user type "-", "1." etc. before it parses.
    const [text, setText] = React.useState<string>(
      value === null || value === undefined ? "" : String(value)
    );

    // Keep text in sync when the value prop changes externally.
    React.useEffect(() => {
      const next = value === null || value === undefined ? "" : String(value);
      setText((prev) => (Number(prev) === value && prev !== "" ? prev : next));
    }, [value]);

    const commit = (next: number | null) => {
      if (!isControlled) setInternal(next);
      onChange?.(next);
    };

    const setNumber = (n: number) => {
      const v = round(clamp(n, min, max), precision);
      setText(String(v));
      commit(v);
    };

    const stepBy = (dir: 1 | -1, multiplier = 1) => {
      const base = value ?? 0;
      setNumber(base + dir * step * multiplier);
    };

    const handleText = (e: React.ChangeEvent<HTMLInputElement>) => {
      const raw = e.target.value;
      setText(raw);
      if (raw === "" || raw === "-") {
        commit(null);
        return;
      }
      const n = Number(raw);
      if (!Number.isNaN(n)) commit(round(n, precision));
    };

    const handleBlur = (e: React.FocusEvent<HTMLInputElement>) => {
      if (value !== null && value !== undefined) {
        const clamped = round(clamp(value, min, max), precision);
        if (clamped !== value) setNumber(clamped);
        else setText(String(clamped));
      } else {
        setText("");
      }
      onBlur?.(e);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (!disabled && !readOnly) {
        if (e.key === "ArrowUp") {
          e.preventDefault();
          stepBy(1, e.shiftKey ? 10 : 1);
        } else if (e.key === "ArrowDown") {
          e.preventDefault();
          stepBy(-1, e.shiftKey ? 10 : 1);
        }
      }
      onKeyDown?.(e);
    };

    const atMin = min !== undefined && value !== null && (value ?? 0) <= min;
    const atMax = max !== undefined && value !== null && (value ?? 0) >= max;

    return (
      <div
        className={cn(
          "vyre-number-input",
          `vyre-number-input--${size}`,
          disabled && "vyre-number-input--disabled",
          className
        )}
        data-disabled={disabled ? "" : undefined}
      >
        <button
          type="button"
          className="vyre-number-input__btn vyre-number-input__btn--dec"
          aria-label="Decrease"
          tabIndex={-1}
          disabled={disabled || readOnly || atMin}
          onClick={() => stepBy(-1)}
        >
          <span aria-hidden="true">−</span>
        </button>
        <input
          ref={ref}
          type="text"
          inputMode="decimal"
          role="spinbutton"
          aria-valuenow={value ?? undefined}
          aria-valuemin={min}
          aria-valuemax={max}
          className="vyre-number-input__field"
          value={text}
          disabled={disabled}
          readOnly={readOnly}
          onChange={handleText}
          onBlur={handleBlur}
          onKeyDown={handleKeyDown}
          {...rest}
        />
        <button
          type="button"
          className="vyre-number-input__btn vyre-number-input__btn--inc"
          aria-label="Increase"
          tabIndex={-1}
          disabled={disabled || readOnly || atMax}
          onClick={() => stepBy(1)}
        >
          <span aria-hidden="true">+</span>
        </button>
      </div>
    );
  }
);
NumberInput.displayName = "VyreNumberInput";
