// packages/react/src/components/Badge/Badge.tsx
/**
 * @usevyre/react — Badge
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────┐
 * │ Component:  Badge                                       │
 * │ Import:     import { Badge } from "@usevyre/react"         │
 * │                                                         │
 * │ Props:                                                  │
 * │   variant = "default"|"accent"|"teal"|                  │
 * │             "success"|"warning"|"danger"                │
 * │   dot     = boolean  (live status dot indicator)        │
 * └─────────────────────────────────────────────────────────┘
 *
 * @example
 * <Badge variant="success" dot>Online</Badge>
 * <Badge variant="warning">Beta</Badge>
 * <Badge variant="danger">Error</Badge>
 */

import React from "react";
import { cn } from "../../utils/cn";
import type { BadgeVariant, BaseProps } from "../../types";

export interface BadgeProps
  extends React.HTMLAttributes<HTMLSpanElement>,
    BaseProps {
  variant?: BadgeVariant;
  /** Show a live status dot indicator */
  dot?: boolean;
}

export const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(
  ({ variant = "default", dot = false, className, children, ...props }, ref) => {
    return (
      <span
        ref={ref}
        className={cn("vyre-badge", `vyre-badge--${variant}`, className)}
        data-variant={variant}
        {...props}
      >
        {dot && <span className="vyre-badge__dot" aria-hidden="true" />}
        {children}
      </span>
    );
  }
);

Badge.displayName = "VyreBadge";

// packages/vue/src/components/Badge/Badge.vue
<script setup lang="ts">
/**
 * @usevyre/vue — Badge
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────┐
 * │ Component:  Badge                                       │
 * │ Import:     import { Badge } from "@usevyre/vue"           │
 * │                                                         │
 * │ Props:                                                  │
 * │   variant = "default"|"accent"|"teal"|                  │
 * │             "success"|"warning"|"danger"                │
 * │   dot     = boolean (show colored dot before label)     │
 * └─────────────────────────────────────────────────────────┘
 *
 * @example
 * <Badge variant="success">Live</Badge>
 * <Badge variant="warning" :dot="true">Beta</Badge>
 * <Badge variant="danger">Deprecated</Badge>
 */

import { computed } from "vue";
import { cn } from "../../utils/cn";

type BadgeVariant = "default" | "accent" | "teal" | "success" | "warning" | "danger";

const props = withDefaults(
  defineProps<{
    variant?: BadgeVariant;
    dot?:     boolean;
    class?:   string;
  }>(),
  { variant: "default", dot: false }
);

const classes = computed(() =>
  cn("vyre-badge", `vyre-badge--${props.variant}`, props.class)
);
</script>

<template>
  <span :class="classes" :data-variant="variant">
    <span v-if="dot" class="vyre-badge__dot" aria-hidden="true" />
    <slot />
  </span>
</template>
