// packages/react/src/components/PieChart/PieChart.tsx
/**
 * @usevyre/react — PieChart
 *
 * AI CONTEXT:
 * ┌──────────────────────────────────────────────────────────────────┐
 * │ Component:  PieChart                                             │
 * │ Import:     import { PieChart } from "@usevyre/react"            │
 * │                                                                   │
 * │ Single-level pie/donut chart. FLAT data (NOT multi-series).       │
 * │   data        = { name: string; value: number }[]  (required)     │
 * │   config      = ChartConfig (optional — { name: {label,color} })  │
 * │                  unmatched names fall back to a token color cycle │
 * │   donut       = boolean (default false — hollow center ring)      │
 * │   size        = number (default 240 — svg width AND height)       │
 * │   showLegend  = boolean (default true — toggleable segments)      │
 * │   showTooltip = boolean (default true — hover segment)            │
 * │                                                                   │
 * │ One <path data-name> per datum; colors come from config or the    │
 * │ documented token cycle. Hidden segments are excluded + total      │
 * │ recomputed from the visible ones.                                 │
 * │                                                                   │
 * │ ANTI-PATTERNS:                                                   │
 * │   ❌ data={[1, 2, 3]}             ✅ data={[{ name, value }]}      │
 * │   ❌ color="blue"                 ✅ config token or auto cycle    │
 * │   ❌ <Pie>/<Cell> children        ✅ data + donut props           │
 * └──────────────────────────────────────────────────────────────────┘
 *
 * @example
 * <PieChart
 *   data={[
 *     { name: "Chrome", value: 60 },
 *     { name: "Safari", value: 25 },
 *     { name: "Firefox", value: 15 },
 *   ]}
 *   donut
 * />
 */
import React from "react";
import { cn } from "../../utils/cn";
import { arcPath } from "../../utils/chart-math";
import type { ChartConfig } from "../Chart/chart-types";
import {
  ChartLegend,
  ChartTooltip,
  useChartTooltip,
  type ChartTooltipRow,
} from "../Chart/ChartParts";

export interface PieDatum {
  name: string;
  value: number;
}

export interface PieChartProps {
  data: PieDatum[];
  config?: ChartConfig;
  donut?: boolean;
  size?: number;
  showLegend?: boolean;
  showTooltip?: boolean;
  className?: string;
}

/** Token color cycle for segments without an explicit config entry. */
const COLOR_CYCLE = [
  "var(--vyre-color-semantic-accent)",
  "var(--vyre-color-semantic-teal)",
  "var(--vyre-color-semantic-success)",
  "var(--vyre-color-semantic-warning)",
  "var(--vyre-color-semantic-danger)",
];

export const PieChart: React.FC<PieChartProps> = ({
  data,
  config,
  donut = false,
  size = 240,
  showLegend = true,
  showTooltip = true,
  className,
}) => {
  const [hidden, setHidden] = React.useState<Record<string, boolean>>({});
  const tooltip = useChartTooltip();

  const onToggle = (name: string) =>
    setHidden((prev) => ({ ...prev, [name]: !prev[name] }));

  const colorFor = (name: string, index: number): string =>
    config?.[name]?.color ?? COLOR_CYCLE[index % COLOR_CYCLE.length];

  // Legend config built from ALL data names (label = name, resolved color).
  const legendConfig: ChartConfig = {};
  data.forEach((d, i) => {
    legendConfig[d.name] = {
      label: config?.[d.name]?.label ?? d.name,
      color: colorFor(d.name, i),
    };
  });

  const cx = size / 2;
  const cy = size / 2;
  const r = size / 2 - 4;
  const innerR = donut ? r * 0.55 : 0;

  // Visible segments only; total recomputed from visible values.
  const visible = data.filter((d) => !hidden[d.name]);
  const total = visible.reduce(
    (sum, d) => sum + (typeof d.value === "number" ? d.value : 0),
    0,
  );

  type Slice = { name: string; color: string; d: string };
  const slices: Slice[] = [];
  if (total > 0) {
    let angle = 0;
    visible.forEach((datum) => {
      // index in original data for stable color resolution.
      const originalIndex = data.indexOf(datum);
      const value = typeof datum.value === "number" ? datum.value : 0;
      const sweep = (value / total) * Math.PI * 2;
      const start = angle;
      const end = angle + sweep;
      angle = end;
      slices.push({
        name: datum.name,
        color: colorFor(datum.name, originalIndex),
        d: arcPath(cx, cy, r, start, end, innerR),
      });
    });
  }

  const ariaLabel = `Pie chart: ${data.length} segments`;

  const rowsForName = (name: string): ChartTooltipRow[] => {
    const datum = data.find((d) => d.name === name);
    return [
      {
        label: legendConfig[name]?.label ?? name,
        value: datum?.value ?? "",
        color: legendConfig[name]?.color ?? "",
      },
    ];
  };

  const handleEnter = (name: string) => {
    if (!showTooltip) return;
    tooltip.show(cx, cy, rowsForName(name));
  };

  const handleLeave = () => {
    if (!showTooltip) return;
    tooltip.hide();
  };

  return (
    <div className={cn("vyre-chart", className)}>
      <svg width={size} height={size} role="img" aria-label={ariaLabel}>
        {slices.map((slice, i) => (
          <path
            key={`${slice.name}-${i}`}
            className="vyre-chart__slice"
            data-name={slice.name}
            d={slice.d}
            fill={slice.color}
            onMouseEnter={showTooltip ? () => handleEnter(slice.name) : undefined}
            onMouseLeave={showTooltip ? handleLeave : undefined}
          />
        ))}
      </svg>
      {showLegend && (
        <ChartLegend config={legendConfig} hidden={hidden} onToggle={onToggle} />
      )}
      {showTooltip && tooltip.active && tooltip.data && (
        <ChartTooltip x={tooltip.data.x} y={tooltip.data.y} rows={tooltip.data.rows} />
      )}
    </div>
  );
};
PieChart.displayName = "VyrePieChart";

// packages/vue/src/components/PieChart/PieChart.vue
<!--
  @usevyre/vue — PieChart

  AI CONTEXT:
  ┌──────────────────────────────────────────────────────────────────┐
  │ Component:  PieChart                                            │
  │ Import:     import { PieChart } from "@usevyre/vue"             │
  │                                                                   │
  │ Single-level pie/donut chart. FLAT data (NOT multi-series).       │
  │   data        = { name: string; value: number }[]  (required)     │
  │   config      = ChartConfig (optional — { name: {label,color} })  │
  │                  unmatched names fall back to a token color cycle │
  │   donut       = boolean (default false — hollow center ring)      │
  │   size        = number (default 240 — svg width AND height)       │
  │   showLegend  = boolean (default true — toggleable segments)      │
  │   showTooltip = boolean (default true — hover segment)            │
  │                                                                   │
  │ One <path data-name> per datum; colors come from config or the    │
  │ documented token cycle. Hidden segments are excluded + total      │
  │ recomputed from the visible ones.                                 │
  │                                                                   │
  │ ANTI-PATTERNS:                                                   │
  │   ❌ data={[1, 2, 3]}             ✅ data={[{ name, value }]}      │
  │   ❌ color="blue"                 ✅ config token or auto cycle    │
  │   ❌ <Pie>/<Cell> children        ✅ data + donut props           │
  └──────────────────────────────────────────────────────────────────┘
-->
<script setup lang="ts">
import { computed, ref } from "vue";
import { cn } from "../../utils/cn";
import { arcPath } from "../../utils/chart-math";
import type { ChartConfig } from "../Chart/chart-types";
import ChartLegend from "../Chart/ChartLegend.vue";
import ChartTooltip from "../Chart/ChartTooltip.vue";
import { useChartTooltip, type ChartTooltipRow } from "../Chart/useChartTooltip";

export interface PieDatum {
  name: string;
  value: number;
}

const props = withDefaults(
  defineProps<{
    data: PieDatum[];
    config?: ChartConfig;
    donut?: boolean;
    size?: number;
    showLegend?: boolean;
    showTooltip?: boolean;
    class?: string;
  }>(),
  {
    donut: false,
    size: 240,
    showLegend: true,
    showTooltip: true,
  }
);

/** Token color cycle for segments without an explicit config entry. */
const COLOR_CYCLE = [
  "var(--vyre-color-semantic-accent)",
  "var(--vyre-color-semantic-teal)",
  "var(--vyre-color-semantic-success)",
  "var(--vyre-color-semantic-warning)",
  "var(--vyre-color-semantic-danger)",
];

const hidden = ref<Record<string, boolean>>({});
const tooltip = useChartTooltip();

const onToggle = (name: string) => {
  hidden.value = { ...hidden.value, [name]: !hidden.value[name] };
};

const colorFor = (name: string, index: number): string =>
  props.config?.[name]?.color ?? COLOR_CYCLE[index % COLOR_CYCLE.length];

const legendConfig = computed<ChartConfig>(() => {
  const cfg: ChartConfig = {};
  props.data.forEach((d, i) => {
    cfg[d.name] = {
      label: props.config?.[d.name]?.label ?? d.name,
      color: colorFor(d.name, i),
    };
  });
  return cfg;
});

const cx = computed(() => props.size / 2);
const cy = computed(() => props.size / 2);
const r = computed(() => props.size / 2 - 4);
const innerR = computed(() => (props.donut ? r.value * 0.55 : 0));

const slices = computed(() => {
  const out: { name: string; color: string; d: string }[] = [];
  const visible = props.data.filter((d) => !hidden.value[d.name]);
  const total = visible.reduce(
    (sum, d) => sum + (typeof d.value === "number" ? d.value : 0),
    0
  );
  if (total > 0) {
    let angle = 0;
    visible.forEach((datum) => {
      const originalIndex = props.data.indexOf(datum);
      const value = typeof datum.value === "number" ? datum.value : 0;
      const sweep = (value / total) * Math.PI * 2;
      const start = angle;
      const end = angle + sweep;
      angle = end;
      out.push({
        name: datum.name,
        color: colorFor(datum.name, originalIndex),
        d: arcPath(cx.value, cy.value, r.value, start, end, innerR.value),
      });
    });
  }
  return out;
});

const ariaLabel = computed(() => `Pie chart: ${props.data.length} segments`);

const rowsForName = (name: string): ChartTooltipRow[] => {
  const datum = props.data.find((d) => d.name === name);
  return [
    {
      label: legendConfig.value[name]?.label ?? name,
      value: datum?.value ?? "",
      color: legendConfig.value[name]?.color ?? "",
    },
  ];
};

const handleEnter = (name: string) => {
  if (!props.showTooltip) return;
  tooltip.show(cx.value, cy.value, rowsForName(name));
};

const handleLeave = () => {
  if (!props.showTooltip) return;
  tooltip.hide();
};
</script>

<template>
  <div :class="cn('vyre-chart', props.class)">
    <svg :width="size" :height="size" role="img" :aria-label="ariaLabel">
      <path
        v-for="(slice, i) in slices"
        :key="`${slice.name}-${i}`"
        class="vyre-chart__slice"
        :data-name="slice.name"
        :d="slice.d"
        :fill="slice.color"
        @mouseenter="showTooltip ? handleEnter(slice.name) : undefined"
        @mouseleave="showTooltip ? handleLeave() : undefined"
      />
    </svg>
    <ChartLegend
      v-if="showLegend"
      :config="legendConfig"
      :hidden="hidden"
      @toggle="onToggle"
    />
    <ChartTooltip
      v-if="showTooltip && tooltip.active.value && tooltip.data.value"
      :x="tooltip.data.value.x"
      :y="tooltip.data.value.y"
      :rows="tooltip.data.value.rows"
    />
  </div>
</template>
