// packages/vue/src/components/TagsInput/TagsInput.vue
<script setup lang="ts">
/**
 * @usevyre/vue — TagsInput
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────┐
 * │ Component:  TagsInput                                   │
 * │ Import:     import { TagsInput } from "@usevyre/vue"    │
 * │                                                         │
 * │ Props:                                                  │
 * │   modelValue  = string[] (v-model)                      │
 * │   placeholder = string                                  │
 * │   disabled    = boolean                                 │
 * │   max         = number — max tag count                  │
 * │   size        = "sm"|"md"(default)|"lg"                 │
 * │                                                         │
 * │ Emits:                                                  │
 * │   update:modelValue — new string[] on every change      │
 * │                                                         │
 * │ Behavior:                                               │
 * │   Enter / comma → add tag (trim, dedupe, skip empty)    │
 * │   Backspace on empty input → remove last tag            │
 * │   × button on tag → remove that tag                     │
 * │   When max reached, input is disabled                   │
 * └─────────────────────────────────────────────────────────┘
 *
 * @example
 * <TagsInput v-model="tags" placeholder="Add tag…" :max="5" />
 *
 * <Field label="Skills">
 *   <TagsInput v-model="skills" />
 * </Field>
 */

import { ref, computed } from "vue";
import { cn } from "../../utils/cn";
import Tag from "../Tag/Tag.vue";

type TagsInputSize = "sm" | "md" | "lg";

const props = withDefaults(
  defineProps<{
    modelValue: string[];
    placeholder?: string;
    disabled?: boolean;
    max?: number;
    size?: TagsInputSize;
    class?: string;
  }>(),
  { placeholder: "Add tag…", disabled: false, size: "md" }
);

const emit = defineEmits<{ "update:modelValue": [tags: string[]] }>();

const inputValue = ref("");
const inputRef = ref<HTMLInputElement | null>(null);

const isMaxReached = computed(
  () => props.max !== undefined && props.modelValue.length >= props.max
);
const isInputDisabled = computed(() => props.disabled || isMaxReached.value);

function addTag(raw: string) {
  const tag = raw.trim();
  if (!tag || props.modelValue.includes(tag) || isMaxReached.value) {
    inputValue.value = "";
    return;
  }
  emit("update:modelValue", [...props.modelValue, tag]);
  inputValue.value = "";
}

function removeTag(index: number) {
  if (props.disabled) return;
  emit("update:modelValue", props.modelValue.filter((_, i) => i !== index));
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter" || e.key === ",") {
    e.preventDefault();
    addTag(inputValue.value);
    return;
  }
  if (e.key === "Backspace" && inputValue.value === "" && props.modelValue.length > 0) {
    removeTag(props.modelValue.length - 1);
  }
}

function onInput(e: Event) {
  const val = (e.target as HTMLInputElement).value;
  if (val.includes(",")) {
    const parts = val.split(",");
    parts.slice(0, -1).forEach((p) => addTag(p));
    inputValue.value = parts[parts.length - 1];
  } else {
    inputValue.value = val;
  }
}

function focusInput() {
  inputRef.value?.focus();
}

const wrapperClasses = computed(() =>
  cn(
    "vyre-tags-input",
    `vyre-tags-input--${props.size}`,
    props.disabled && "vyre-tags-input--disabled",
    props.class
  )
);
</script>

<template>
  <div :class="wrapperClasses" @click="focusInput">
    <Tag
      v-for="(tag, index) in modelValue"
      :key="`${tag}-${index}`"
      :size="size"
      :disabled="disabled"
      :removable="!disabled"
      @remove="removeTag(index)"
    >
      {{ tag }}
    </Tag>
    <input
      ref="inputRef"
      type="text"
      class="vyre-tags-input__field"
      :value="inputValue"
      :placeholder="isMaxReached ? '' : placeholder"
      :disabled="isInputDisabled"
      aria-label="Add tag"
      @input="onInput"
      @keydown="onKeyDown"
    />
  </div>
</template>

// packages/react/src/components/TagsInput/TagsInput.tsx
/**
 * @usevyre/react — TagsInput
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────┐
 * │ Component:  TagsInput                                   │
 * │ Import:     import { TagsInput } from "@usevyre/react"  │
 * │                                                         │
 * │ Props:                                                  │
 * │   value       = string[] (controlled)                   │
 * │   onChange    = (tags: string[]) => void                │
 * │   placeholder = string                                  │
 * │   disabled    = boolean                                 │
 * │   max         = number — max tag count                  │
 * │   size        = "sm"|"md"(default)|"lg"                 │
 * │                                                         │
 * │ Behavior:                                               │
 * │   Enter / comma → add tag (trim, dedupe, skip empty)    │
 * │   Backspace on empty input → remove last tag            │
 * │   × button on tag → remove that tag                     │
 * │   When max reached, input is disabled                   │
 * └─────────────────────────────────────────────────────────┘
 *
 * @example
 * const [tags, setTags] = useState(["react", "typescript"]);
 * <TagsInput value={tags} onChange={setTags} placeholder="Add tag…" max={5} />
 *
 * // Inside a Field
 * <Field label="Skills">
 *   <TagsInput value={skills} onChange={setSkills} />
 * </Field>
 */

import React, { useState, useRef } from "react";
import { cn } from "../../utils/cn";
import { Tag } from "../Tag/Tag";
import type { BaseProps } from "../../types";

type TagsInputSize = "sm" | "md" | "lg";

export interface TagsInputProps extends BaseProps {
  /** Controlled tag list */
  value: string[];
  /** Called with new tag array on every change */
  onChange: (tags: string[]) => void;
  /** Input placeholder (hidden when max reached) */
  placeholder?: string;
  /** Disable all interactions */
  disabled?: boolean;
  /** Maximum number of tags allowed */
  max?: number;
  /** Size scale */
  size?: TagsInputSize;
}

export const TagsInput = React.forwardRef<HTMLDivElement, TagsInputProps>(
  (
    {
      value,
      onChange,
      placeholder = "Add tag…",
      disabled = false,
      max,
      size = "md",
      className,
      style,
      "data-testid": testId,
    },
    ref
  ) => {
    const [inputValue, setInputValue] = useState("");
    const inputRef = useRef<HTMLInputElement>(null);

    const isMaxReached = max !== undefined && value.length >= max;
    const isInputDisabled = disabled || isMaxReached;

    function addTag(raw: string) {
      const tag = raw.trim();
      if (!tag || value.includes(tag) || isMaxReached) {
        setInputValue("");
        return;
      }
      onChange([...value, tag]);
      setInputValue("");
    }

    function removeTag(index: number) {
      if (disabled) return;
      onChange(value.filter((_, i) => i !== index));
    }

    function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
      if (e.key === "Enter" || e.key === ",") {
        e.preventDefault();
        addTag(inputValue);
        return;
      }
      if (e.key === "Backspace" && inputValue === "" && value.length > 0) {
        removeTag(value.length - 1);
      }
    }

    function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
      const val = e.target.value;
      // Auto-split on comma paste
      if (val.includes(",")) {
        const parts = val.split(",");
        const toAdd = parts.slice(0, -1);
        toAdd.forEach((p) => addTag(p));
        setInputValue(parts[parts.length - 1]);
      } else {
        setInputValue(val);
      }
    }

    return (
      <div
        ref={ref}
        className={cn(
          "vyre-tags-input",
          `vyre-tags-input--${size}`,
          disabled && "vyre-tags-input--disabled",
          className
        )}
        data-testid={testId}
        style={style}
        onClick={() => inputRef.current?.focus()}
      >
        {value.map((tag, index) => (
          <Tag
            key={`${tag}-${index}`}
            size={size}
            disabled={disabled}
            onRemove={disabled ? undefined : () => removeTag(index)}
          >
            {tag}
          </Tag>
        ))}
        <input
          ref={inputRef}
          type="text"
          className="vyre-tags-input__field"
          value={inputValue}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          placeholder={isMaxReached ? "" : placeholder}
          disabled={isInputDisabled}
          aria-label="Add tag"
        />
      </div>
    );
  }
);

TagsInput.displayName = "VyreTagsInput";
