// packages/react/src/components/Progress/Progress.tsx
/**
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────┐
 * │ Component:  Progress                        │
 * │ value       = number (0-100)                │
 * │ max         = number (default: 100)         │
 * │ indeterminate = boolean                     │
 * │ size        = "sm"|"md"(default)|"lg"       │
 * │ variant     = "default"|"accent"|"teal"|"success"|"danger" │
 * │ CSS class:  .vyre-progress                  │
 * └─────────────────────────────────────────────┘
 */

import React from "react";

export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> {
  value?: number;
  max?: number;
  indeterminate?: boolean;
  size?: "sm" | "md" | "lg";
  variant?: "default" | "accent" | "teal" | "success" | "danger";
}

export const Progress = React.forwardRef<HTMLDivElement, ProgressProps>(
  (
    {
      value,
      max = 100,
      indeterminate = false,
      size = "md",
      variant = "default",
      className,
      ...props
    },
    ref
  ) => {
    const percentage = indeterminate
      ? undefined
      : Math.min(100, Math.max(0, ((value ?? 0) / max) * 100));

    return (
      <div
        ref={ref}
        role="progressbar"
        aria-valuemin={0}
        aria-valuemax={max}
        aria-valuenow={indeterminate ? undefined : (value ?? 0)}
        data-size={size}
        data-variant={variant}
        data-indeterminate={indeterminate || undefined}
        className={["vyre-progress", className].filter(Boolean).join(" ")}
        {...props}
      >
        <div
          className="vyre-progress__bar"
          style={percentage !== undefined ? { width: `${percentage}%` } : undefined}
        />
      </div>
    );
  }
);
Progress.displayName = "Progress";

// packages/vue/src/components/Progress/Progress.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(defineProps<{
  value?: number;
  max?: number;
  indeterminate?: boolean;
  size?: "sm" | "md" | "lg";
  variant?: "default" | "accent" | "teal" | "success" | "danger";
  class?: string;
}>(), { max: 100, size: "md", variant: "default" });

const percentage = computed(() =>
  props.indeterminate
    ? undefined
    : Math.min(100, Math.max(0, ((props.value ?? 0) / props.max!) * 100))
);
</script>

<template>
  <div
    role="progressbar"
    :aria-valuemin="0"
    :aria-valuemax="max"
    :aria-valuenow="indeterminate ? undefined : (value ?? 0)"
    :data-size="size"
    :data-variant="variant"
    :data-indeterminate="indeterminate || undefined"
    :class="['vyre-progress', $props.class]"
  >
    <div
      class="vyre-progress__bar"
      :style="percentage !== undefined ? { width: `${percentage}%` } : undefined"
    />
  </div>
</template>
