// packages/react/src/components/BarChart/BarChart.tsx
/**
 * @usevyre/react — BarChart
 *
 * AI CONTEXT:
 * ┌──────────────────────────────────────────────────────────────────┐
 * │ Component:  BarChart                                             │
 * │ Import:     import { BarChart } from "@usevyre/react"             │
 * │                                                                   │
 * │ Multi-series bar chart. Data + config driven (NOT JSX children).  │
 * │   data        = ChartDatum[]  (required — array of row objects)   │
 * │   config      = ChartConfig   (required — { key: {label,color} }) │
 * │   xKey        = string        (required — the x-axis field name)  │
 * │   orientation = "vertical"(default) | "horizontal"               │
 * │   stacked     = boolean (default false — accumulate series)       │
 * │   width       = number (default 480)   height = number (240)      │
 * │   showGrid    = boolean (default true)                            │
 * │   showLegend  = boolean (default true — toggleable series)        │
 * │   showTooltip = boolean (default true — hover + arrow keys)       │
 * │                                                                   │
 * │ x-axis is BANDED by data index (one band per datum). Multiple     │
 * │ series → grouped side-by-side bars, or stacked when stacked.      │
 * │ One <rect data-series> per bar; colors come ONLY from config.     │
 * │                                                                   │
 * │ ANTI-PATTERNS:                                                    │
 * │   ❌ series={...}                 ✅ data + config                 │
 * │   ❌ color="blue"                 ✅ color token in config         │
 * │   ❌ <XAxis/> / <Tooltip/> kids   ✅ showGrid / showTooltip props  │
 * └──────────────────────────────────────────────────────────────────┘
 *
 * @example
 * <BarChart
 *   data={[{ region: "NA", sales: 30 }, { region: "EU", sales: 25 }]}
 *   config={{ sales: { label: "Sales", color: "var(--vyre-color-semantic-accent)" } }}
 *   xKey="region"
 * />
 */
import React from "react";
import { cn } from "../../utils/cn";
import { scaleLinear, niceTicks } from "../../utils/chart-math";
import type { ChartConfig, ChartDatum } from "../Chart/chart-types";
import {
  ChartGrid,
  ChartLegend,
  ChartTooltip,
  useChartTooltip,
  type ChartTooltipRow,
} from "../Chart/ChartParts";

export interface BarChartProps {
  data: ChartDatum[];
  config: ChartConfig;
  xKey: string;
  orientation?: "vertical" | "horizontal";
  stacked?: boolean;
  width?: number;
  height?: number;
  showGrid?: boolean;
  showLegend?: boolean;
  showTooltip?: boolean;
  className?: string;
}

const PAD = { left: 32, right: 8, top: 8, bottom: 24 };
const BAND_INNER_PAD = 0.2;

export const BarChart: React.FC<BarChartProps> = ({
  data,
  config,
  xKey,
  orientation = "vertical",
  stacked = false,
  width = 480,
  height = 240,
  showGrid = true,
  showLegend = true,
  showTooltip = true,
  className,
}) => {
  const seriesKeys = Object.keys(config);
  const [hidden, setHidden] = React.useState<Record<string, boolean>>({});
  const [activeIndex, setActiveIndex] = React.useState<number | null>(null);
  const tooltip = useChartTooltip();
  const svgRef = React.useRef<SVGSVGElement | null>(null);

  const onToggle = (key: string) =>
    setHidden((prev) => ({ ...prev, [key]: !prev[key] }));

  const visibleKeys = seriesKeys.filter((k) => !hidden[k]);

  const num = (v: unknown) => (typeof v === "number" ? v : 0);

  // value-domain across all visible series (always include 0).
  // When stacked, the domain top is the per-row sum of visible series.
  const values: number[] = [0];
  for (const row of data) {
    if (stacked) {
      let sum = 0;
      for (const key of visibleKeys) sum += num(row[key]);
      values.push(sum);
    } else {
      for (const key of visibleKeys) values.push(num(row[key]));
    }
  }
  const vMin = Math.min(...values);
  const vMax = Math.max(...values);

  const innerWidth = width - PAD.left - PAD.right;
  const innerHeight = height - PAD.top - PAD.bottom;

  const isVertical = orientation === "vertical";

  // value scale maps the data value onto the value axis.
  // vertical → y (top is vMax), horizontal → x (right is vMax).
  const valueScale = isVertical
    ? scaleLinear([vMin, vMax], [PAD.top + innerHeight, PAD.top])
    : scaleLinear([vMin, vMax], [PAD.left, width - PAD.right]);
  const ticks = niceTicks(vMin, vMax);

  // banded category axis: one band per datum along the cross axis.
  const n = Math.max(data.length, 1);
  const bandSpan = (isVertical ? innerWidth : innerHeight) / n;
  const bandStart = isVertical ? PAD.left : PAD.top;
  const innerBand = bandSpan * (1 - BAND_INNER_PAD);
  const bandPadOffset = (bandSpan - innerBand) / 2;
  const slotCount = stacked ? 1 : Math.max(visibleKeys.length, 1);
  const slotSize = innerBand / slotCount;

  // zero position on the value axis (where bars originate from).
  const valueZero = valueScale(Math.max(vMin, 0));

  type Bar = { key: string; x: number; y: number; w: number; h: number };
  const bars: Bar[] = [];
  data.forEach((row, i) => {
    const bandOrigin = bandStart + i * bandSpan + bandPadOffset;
    let stackAcc = 0;
    visibleKeys.forEach((key, si) => {
      const value = num(row[key]);
      if (isVertical) {
        const slotX = stacked ? bandOrigin : bandOrigin + si * slotSize;
        if (stacked) {
          const top = valueScale(stackAcc + value);
          const base = valueScale(stackAcc);
          stackAcc += value;
          bars.push({ key, x: slotX, y: top, w: innerBand, h: Math.abs(base - top) });
        } else {
          const top = valueScale(value);
          bars.push({ key, x: slotX, y: Math.min(top, valueZero), w: slotSize, h: Math.abs(valueZero - top) });
        }
      } else {
        const slotY = stacked ? bandOrigin : bandOrigin + si * slotSize;
        if (stacked) {
          const end = valueScale(stackAcc + value);
          const base = valueScale(stackAcc);
          stackAcc += value;
          bars.push({ key, x: Math.min(base, end), y: slotY, w: Math.abs(end - base), h: innerBand });
        } else {
          const end = valueScale(value);
          bars.push({ key, x: Math.min(valueZero, end), y: slotY, w: Math.abs(end - valueZero), h: slotSize });
        }
      }
    });
  });

  const seriesLabels = seriesKeys.map((k) => config[k].label).join(", ");
  const xLabels = data.map((row) => String(row[xKey] ?? ""));
  const ariaLabel = `Bar chart: ${seriesLabels} across ${data.length} categories`;

  const rowsForIndex = (index: number): ChartTooltipRow[] =>
    visibleKeys.map((key) => ({
      label: config[key].label,
      value: data[index]?.[key] ?? "",
      color: config[key].color,
    }));

  const bandCenter = (index: number) =>
    bandStart + index * bandSpan + bandSpan / 2;

  // Convert a data index to PIXEL coords inside the rendered svg (= the
  // .vyre-chart container box, since the svg is width:100% of it).
  const pixelForIndex = (index: number): { x: number; y: number } | null => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || rect.width === 0) return null;
    const center = bandCenter(index);
    const xView = isVertical ? center : valueScale(vMax);
    const yView = isVertical ? valueScale(vMax) : center;
    return {
      x: (xView / width) * rect.width,
      y: (yView / height) * rect.height,
    };
  };

  // Place the tooltip at the data point (keyboard nav).
  const showTooltipAt = (index: number) => {
    if (data.length === 0) return;
    const clamped = Math.max(0, Math.min(data.length - 1, index));
    setActiveIndex(clamped);
    const px = pixelForIndex(clamped);
    if (px) tooltip.show(px.x + 12, px.y + 12, rowsForIndex(clamped), xLabels[clamped]);
  };

  const handleMouseMove = (e: React.MouseEvent<SVGSVGElement>) => {
    if (!showTooltip || data.length === 0) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const mxPx = e.clientX - rect.left;
    const myPx = e.clientY - rect.top;
    // band detection happens in viewBox space along the category axis.
    const posPx = isVertical ? mxPx : myPx;
    const renderedSpan = isVertical ? rect.width : rect.height;
    const viewSpan = isVertical ? width : height;
    const posView = renderedSpan === 0 ? posPx : (posPx / renderedSpan) * viewSpan;
    const index = Math.floor((posView - bandStart) / bandSpan);
    const clamped = Math.max(0, Math.min(data.length - 1, index));
    setActiveIndex(clamped);
    tooltip.show(mxPx + 12, myPx + 12, rowsForIndex(clamped), xLabels[clamped]);
  };

  const handleMouseLeave = () => {
    if (!showTooltip) return;
    setActiveIndex(null);
    tooltip.hide();
  };

  const handleKeyDown = (e: React.KeyboardEvent<SVGSVGElement>) => {
    if (!showTooltip || data.length === 0) return;
    if (e.key === "ArrowLeft") {
      e.preventDefault();
      showTooltipAt((activeIndex ?? 0) - 1);
    } else if (e.key === "ArrowRight") {
      e.preventDefault();
      showTooltipAt((activeIndex ?? -1) + 1);
    }
  };

  return (
    <div className={cn("vyre-chart", className)}>
      <svg
        ref={svgRef}
        width={width}
        height={height}
        viewBox={`0 0 ${width} ${height}`}
        role="img"
        aria-label={ariaLabel}
        tabIndex={showTooltip ? 0 : undefined}
        onMouseMove={showTooltip ? handleMouseMove : undefined}
        onMouseLeave={showTooltip ? handleMouseLeave : undefined}
        onKeyDown={showTooltip ? handleKeyDown : undefined}
      >
        {showGrid && isVertical && (
          <g transform={`translate(${PAD.left}, 0)`}>
            <ChartGrid ticks={ticks} scaleY={valueScale} width={innerWidth} />
          </g>
        )}
        {bars.map((bar, i) => (
          <rect
            key={`${bar.key}-${i}`}
            className="vyre-chart__bar"
            data-series={bar.key}
            x={bar.x}
            y={bar.y}
            width={bar.w}
            height={bar.h}
            fill={config[bar.key].color}
          />
        ))}
        {showGrid &&
          xLabels.map((label, i) => (
            <text
              key={`x-${i}`}
              className="vyre-chart__axis-label"
              x={isVertical ? bandCenter(i) : PAD.left}
              y={isVertical ? height - PAD.bottom + 16 : bandCenter(i)}
              textAnchor={isVertical ? "middle" : "end"}
            >
              {label}
            </text>
          ))}
      </svg>
      {showLegend && (
        <ChartLegend config={config} hidden={hidden} onToggle={onToggle} />
      )}
      {showTooltip && tooltip.active && tooltip.data && (
        <ChartTooltip x={tooltip.data.x} y={tooltip.data.y} rows={tooltip.data.rows} title={tooltip.data.title} />
      )}
    </div>
  );
};
BarChart.displayName = "VyreBarChart";

// packages/vue/src/components/BarChart/BarChart.vue
<!--
  @usevyre/vue — BarChart

  AI CONTEXT:
  ┌──────────────────────────────────────────────────────────────────┐
  │ Component:  BarChart                                             │
  │ Import:     import { BarChart } from "@usevyre/vue"              │
  │                                                                   │
  │ Multi-series bar chart. Data + config driven (NOT slot children). │
  │   data        = ChartDatum[]  (required — array of row objects)   │
  │   config      = ChartConfig   (required — { key: {label,color} }) │
  │   xKey        = string        (required — the x-axis field name)  │
  │   orientation = "vertical"(default) | "horizontal"               │
  │   stacked     = boolean (default false — accumulate series)       │
  │   width       = number (default 480)   height = number (240)      │
  │   showGrid    = boolean (default true)                            │
  │   showLegend  = boolean (default true — toggleable series)        │
  │   showTooltip = boolean (default true — hover + arrow keys)       │
  │                                                                   │
  │ x-axis is BANDED by data index (one band per datum). Multiple     │
  │ series → grouped side-by-side bars, or stacked when stacked.      │
  │ One <rect data-series> per bar; colors come ONLY from config.     │
  │                                                                   │
  │ ANTI-PATTERNS:                                                    │
  │   ❌ series={...}                 ✅ data + config                 │
  │   ❌ color="blue"                 ✅ color token in config         │
  │   ❌ <XAxis/> / <Tooltip/> kids   ✅ showGrid / showTooltip props  │
  └──────────────────────────────────────────────────────────────────┘
-->
<script setup lang="ts">
import { computed, ref } from "vue";
import { cn } from "../../utils/cn";
import { scaleLinear, niceTicks } from "../../utils/chart-math";
import type { ChartConfig, ChartDatum } from "../Chart/chart-types";
import ChartGrid from "../Chart/ChartGrid.vue";
import ChartLegend from "../Chart/ChartLegend.vue";
import ChartTooltip from "../Chart/ChartTooltip.vue";
import { useChartTooltip, type ChartTooltipRow } from "../Chart/useChartTooltip";

const props = withDefaults(
  defineProps<{
    data: ChartDatum[];
    config: ChartConfig;
    xKey: string;
    orientation?: "vertical" | "horizontal";
    stacked?: boolean;
    width?: number;
    height?: number;
    showGrid?: boolean;
    showLegend?: boolean;
    showTooltip?: boolean;
    class?: string;
  }>(),
  {
    orientation: "vertical",
    stacked: false,
    width: 480,
    height: 240,
    showGrid: true,
    showLegend: true,
    showTooltip: true,
  }
);

const PAD = { left: 32, right: 8, top: 8, bottom: 24 };
const BAND_INNER_PAD = 0.2;

const hidden = ref<Record<string, boolean>>({});
const activeIndex = ref<number | null>(null);
const tooltip = useChartTooltip();
const svgRef = ref<SVGSVGElement | null>(null);

const seriesKeys = computed(() => Object.keys(props.config));
const visibleKeys = computed(() => seriesKeys.value.filter((k) => !hidden.value[k]));

const onToggle = (key: string) => {
  hidden.value = { ...hidden.value, [key]: !hidden.value[key] };
};

const num = (v: unknown) => (typeof v === "number" ? v : 0);

const isVertical = computed(() => props.orientation === "vertical");
const innerWidth = computed(() => props.width - PAD.left - PAD.right);
const innerHeight = computed(() => props.height - PAD.top - PAD.bottom);

const domain = computed(() => {
  const values: number[] = [0];
  for (const row of props.data) {
    if (props.stacked) {
      let sum = 0;
      for (const key of visibleKeys.value) sum += num(row[key]);
      values.push(sum);
    } else {
      for (const key of visibleKeys.value) values.push(num(row[key]));
    }
  }
  return { vMin: Math.min(...values), vMax: Math.max(...values) };
});

const valueScale = computed(() =>
  isVertical.value
    ? scaleLinear([domain.value.vMin, domain.value.vMax], [PAD.top + innerHeight.value, PAD.top])
    : scaleLinear([domain.value.vMin, domain.value.vMax], [PAD.left, props.width - PAD.right])
);
const ticks = computed(() => niceTicks(domain.value.vMin, domain.value.vMax));

const n = computed(() => Math.max(props.data.length, 1));
const bandSpan = computed(() => (isVertical.value ? innerWidth.value : innerHeight.value) / n.value);
const bandStart = computed(() => (isVertical.value ? PAD.left : PAD.top));
const innerBand = computed(() => bandSpan.value * (1 - BAND_INNER_PAD));
const bandPadOffset = computed(() => (bandSpan.value - innerBand.value) / 2);
const slotCount = computed(() => (props.stacked ? 1 : Math.max(visibleKeys.value.length, 1)));
const slotSize = computed(() => innerBand.value / slotCount.value);

const bandCenter = (index: number) =>
  bandStart.value + index * bandSpan.value + bandSpan.value / 2;

const bars = computed(() => {
  const out: { key: string; x: number; y: number; w: number; h: number; color: string }[] = [];
  const valueZero = valueScale.value(Math.max(domain.value.vMin, 0));
  props.data.forEach((row, i) => {
    const bandOrigin = bandStart.value + i * bandSpan.value + bandPadOffset.value;
    let stackAcc = 0;
    visibleKeys.value.forEach((key, si) => {
      const value = num(row[key]);
      const color = props.config[key].color;
      if (isVertical.value) {
        const slotX = props.stacked ? bandOrigin : bandOrigin + si * slotSize.value;
        if (props.stacked) {
          const top = valueScale.value(stackAcc + value);
          const base = valueScale.value(stackAcc);
          stackAcc += value;
          out.push({ key, x: slotX, y: top, w: innerBand.value, h: Math.abs(base - top), color });
        } else {
          const top = valueScale.value(value);
          out.push({ key, x: slotX, y: Math.min(top, valueZero), w: slotSize.value, h: Math.abs(valueZero - top), color });
        }
      } else {
        const slotY = props.stacked ? bandOrigin : bandOrigin + si * slotSize.value;
        if (props.stacked) {
          const end = valueScale.value(stackAcc + value);
          const base = valueScale.value(stackAcc);
          stackAcc += value;
          out.push({ key, x: Math.min(base, end), y: slotY, w: Math.abs(end - base), h: innerBand.value, color });
        } else {
          const end = valueScale.value(value);
          out.push({ key, x: Math.min(valueZero, end), y: slotY, w: Math.abs(end - valueZero), h: slotSize.value, color });
        }
      }
    });
  });
  return out;
});

const xLabels = computed(() => props.data.map((row) => String(row[props.xKey] ?? "")));

const ariaLabel = computed(() => {
  const seriesLabels = seriesKeys.value.map((k) => props.config[k].label).join(", ");
  return `Bar chart: ${seriesLabels} across ${props.data.length} categories`;
});

const rowsForIndex = (index: number): ChartTooltipRow[] =>
  visibleKeys.value.map((key) => ({
    label: props.config[key].label,
    value: props.data[index]?.[key] ?? "",
    color: props.config[key].color,
  }));

// Convert a data index to PIXEL coords inside the rendered svg (= the
// .vyre-chart container box, since the svg is width:100% of it).
const pixelForIndex = (index: number): { x: number; y: number } | null => {
  const rect = svgRef.value?.getBoundingClientRect();
  if (!rect || rect.width === 0) return null;
  const center = bandCenter(index);
  const xView = isVertical.value ? center : valueScale.value(domain.value.vMax);
  const yView = isVertical.value ? valueScale.value(domain.value.vMax) : center;
  return {
    x: (xView / props.width) * rect.width,
    y: (yView / props.height) * rect.height,
  };
};

// Place the tooltip at the data point (keyboard nav).
const showTooltipAt = (index: number) => {
  if (props.data.length === 0) return;
  const clamped = Math.max(0, Math.min(props.data.length - 1, index));
  activeIndex.value = clamped;
  const px = pixelForIndex(clamped);
  if (px) tooltip.show(px.x + 12, px.y + 12, rowsForIndex(clamped), xLabels.value[clamped]);
};

const handleMouseMove = (e: MouseEvent) => {
  if (!props.showTooltip || props.data.length === 0) return;
  const rect = (e.currentTarget as SVGSVGElement).getBoundingClientRect();
  const mxPx = e.clientX - rect.left;
  const myPx = e.clientY - rect.top;
  // band detection happens in viewBox space along the category axis.
  const posPx = isVertical.value ? mxPx : myPx;
  const renderedSpan = isVertical.value ? rect.width : rect.height;
  const viewSpan = isVertical.value ? props.width : props.height;
  const posView = renderedSpan === 0 ? posPx : (posPx / renderedSpan) * viewSpan;
  const index = Math.floor((posView - bandStart.value) / bandSpan.value);
  const clamped = Math.max(0, Math.min(props.data.length - 1, index));
  activeIndex.value = clamped;
  tooltip.show(mxPx + 12, myPx + 12, rowsForIndex(clamped), xLabels.value[clamped]);
};

const handleMouseLeave = () => {
  if (!props.showTooltip) return;
  activeIndex.value = null;
  tooltip.hide();
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (!props.showTooltip || props.data.length === 0) return;
  if (e.key === "ArrowLeft") {
    e.preventDefault();
    showTooltipAt((activeIndex.value ?? 0) - 1);
  } else if (e.key === "ArrowRight") {
    e.preventDefault();
    showTooltipAt((activeIndex.value ?? -1) + 1);
  }
};
</script>

<template>
  <div :class="cn('vyre-chart', props.class)">
    <svg
      ref="svgRef"
      :width="width"
      :height="height"
      :view-box="`0 0 ${width} ${height}`"
      role="img"
      :aria-label="ariaLabel"
      :tabindex="showTooltip ? 0 : undefined"
      @mousemove="showTooltip ? handleMouseMove($event) : undefined"
      @mouseleave="showTooltip ? handleMouseLeave() : undefined"
      @keydown="showTooltip ? handleKeyDown($event) : undefined"
    >
      <g v-if="showGrid && isVertical" :transform="`translate(${PAD.left}, 0)`">
        <ChartGrid :ticks="ticks" :scale-y="valueScale" :width="innerWidth" />
      </g>
      <rect
        v-for="(bar, i) in bars"
        :key="`${bar.key}-${i}`"
        class="vyre-chart__bar"
        :data-series="bar.key"
        :x="bar.x"
        :y="bar.y"
        :width="bar.w"
        :height="bar.h"
        :fill="bar.color"
      />
      <template v-if="showGrid">
        <text
          v-for="(label, i) in xLabels"
          :key="`x-${i}`"
          class="vyre-chart__axis-label"
          :x="isVertical ? bandCenter(i) : PAD.left"
          :y="isVertical ? height - PAD.bottom + 16 : bandCenter(i)"
          :text-anchor="isVertical ? 'middle' : 'end'"
        >
          {{ label }}
        </text>
      </template>
    </svg>
    <ChartLegend
      v-if="showLegend"
      :config="config"
      :hidden="hidden"
      @toggle="onToggle"
    />
    <ChartTooltip
      v-if="showTooltip && tooltip.active.value && tooltip.data.value"
      :x="tooltip.data.value.x"
      :y="tooltip.data.value.y"
      :rows="tooltip.data.value.rows"
      :title="tooltip.data.value.title"
    />
  </div>
</template>
