// packages/react/src/components/Skeleton/Skeleton.tsx
/**
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────┐
 * │ Component:  Skeleton                        │
 * │ variant = "text"|"circle"|"rect"(default)   │
 * │ width   = string | number                   │
 * │ height  = string | number                   │
 * │ CSS class:  .vyre-skeleton                  │
 * └─────────────────────────────────────────────┘
 */

import React from "react";

export interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: "rect" | "circle" | "text";
  width?: string | number;
  height?: string | number;
}

export const Skeleton = React.forwardRef<HTMLDivElement, SkeletonProps>(
  ({ variant = "rect", width, height, className, style, ...props }, ref) => {
    return (
      <div
        ref={ref}
        aria-hidden="true"
        data-variant={variant}
        className={["vyre-skeleton", className].filter(Boolean).join(" ")}
        style={{
          width: typeof width === "number" ? `${width}px` : width,
          height: typeof height === "number" ? `${height}px` : height,
          ...style,
        }}
        {...props}
      />
    );
  }
);
Skeleton.displayName = "Skeleton";

// packages/vue/src/components/Skeleton/Skeleton.vue
<script setup lang="ts">
withDefaults(defineProps<{
  variant?: "rect" | "circle" | "text";
  width?: string | number;
  height?: string | number;
  class?: string;
}>(), { variant: "rect" });

const px = (v?: string | number) =>
  v === undefined ? undefined : typeof v === "number" ? `${v}px` : v;
</script>

<template>
  <div
    aria-hidden="true"
    :data-variant="variant"
    :class="['vyre-skeleton', $props.class]"
    :style="{ width: px(width), height: px(height) }"
  />
</template>
