// packages/vue/src/components/Label/Label.vue
<script setup lang="ts">
withDefaults(defineProps<{
  for?: string;
  required?: boolean;
  disabled?: boolean;
  class?: string;
}>(), {});
</script>

<template>
  <label
    :for="$props.for"
    :data-required="required || undefined"
    :data-disabled="disabled || undefined"
    :class="['vyre-label', $props.class]"
  >
    <slot />
    <span v-if="required" class="vyre-label__required" aria-hidden="true">*</span>
  </label>
</template>

// packages/react/src/components/Label/Label.tsx
/**
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────┐
 * │ Component:  Label                           │
 * │ htmlFor    = string (links to input id)     │
 * │ required   = boolean                        │
 * │ disabled   = boolean                        │
 * │ CSS class:  .vyre-label                     │
 * └─────────────────────────────────────────────┘
 */

import React from "react";

export interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  required?: boolean;
  disabled?: boolean;
}

export const Label = React.forwardRef<HTMLLabelElement, LabelProps>(
  ({ required, disabled, className, children, ...props }, ref) => {
    return (
      <label
        ref={ref}
        data-required={required || undefined}
        data-disabled={disabled || undefined}
        className={["vyre-label", className].filter(Boolean).join(" ")}
        {...props}
      >
        {children}
        {required && <span className="vyre-label__required" aria-hidden="true">*</span>}
      </label>
    );
  }
);
Label.displayName = "Label";
