// packages/react/src/components/Popover/Popover.tsx
/**
 * @usevyre/react — Popover
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────┐
 * │ Component:  Popover                                     │
 * │ Import:     import { Popover } from "@usevyre/react"       │
 * │                                                         │
 * │ Props:                                                  │
 * │   open           = boolean (controlled)                 │
 * │   onOpenChange   = (open: boolean) => void              │
 * │   placement      = "bottom"(default)                    │
 * │                    side: "top"|"bottom"|"left"|"right"  │
 * │                    align: "-start"?|""?|"-end"?         │
 * │                    e.g. "top-start", "bottom-end",      │
 * │                         "left", "right-start"           │
 * │   trigger        = ReactElement (the anchor element)    │
 * │   children       = ReactNode (popover content)          │
 * │   closeOnOutside = boolean (default: true)              │
 * └─────────────────────────────────────────────────────────┘
 *
 * @example
 * // Controlled
 * <Popover open={open} onOpenChange={setOpen} trigger={<Button>Open</Button>}>
 *   <p>Content here.</p>
 * </Popover>
 *
 * // Uncontrolled
 * <Popover placement="bottom-start" trigger={<Button>Open</Button>}>
 *   <p>Content here.</p>
 * </Popover>
 */

import React, { useState, useRef, useEffect, useId, useCallback } from "react";
import ReactDOM from "react-dom";
import { cn } from "../../utils/cn";

export type PopoverSide      = "top" | "bottom" | "left" | "right";
export type PopoverAlign     = "start" | "center" | "end";
export type PopoverPlacement =
  | "top" | "top-start" | "top-end"
  | "bottom" | "bottom-start" | "bottom-end"
  | "left" | "left-start" | "left-end"
  | "right" | "right-start" | "right-end";

export interface PopoverProps {
  trigger: React.ReactElement;
  children: React.ReactNode;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  placement?: PopoverPlacement;
  closeOnOutside?: boolean;
  className?: string;
}

const GAP = 8;
const ANIM_OUT_MS = 120;

function parsePlacement(placement: PopoverPlacement): { side: PopoverSide; align: PopoverAlign } {
  const [side, align] = placement.split("-") as [PopoverSide, PopoverAlign | undefined];
  return { side, align: align ?? "center" };
}

/**
 * Compute `top` and `left` for the popover such that it sits on the correct
 * side of the trigger with the correct alignment.
 * All values are in page coordinates (rect + scroll).
 */
function computePosition(
  triggerRect: DOMRect,
  popoverRect: DOMRect,
  side: PopoverSide,
  align: PopoverAlign,
  scrollX: number,
  scrollY: number,
): { top: number; left: number } {
  const tw = triggerRect.width;
  const th = triggerRect.height;
  const pw = popoverRect.width;
  const ph = popoverRect.height;
  const tx = triggerRect.left + scrollX;
  const ty = triggerRect.top  + scrollY;

  let top = 0, left = 0;

  // ── side ──────────────────────────────────────────────────
  switch (side) {
    case "top":    top = ty - ph - GAP;           break;
    case "bottom": top = ty + th + GAP;           break;
    case "left":   left = tx - pw - GAP;          break;
    case "right":  left = tx + tw + GAP;          break;
  }

  // ── alignment on the cross axis ───────────────────────────
  if (side === "top" || side === "bottom") {
    switch (align) {
      case "start":  left = tx;                   break;
      case "center": left = tx + tw / 2 - pw / 2; break;
      case "end":    left = tx + tw - pw;          break;
    }
  } else {
    // left | right
    switch (align) {
      case "start":  top = ty;                    break;
      case "center": top = ty + th / 2 - ph / 2; break;
      case "end":    top = ty + th - ph;          break;
    }
  }

  return { top, left };
}

export const Popover: React.FC<PopoverProps> = ({
  trigger,
  children,
  open: controlledOpen,
  onOpenChange,
  placement = "bottom",
  closeOnOutside = true,
  className,
}) => {
  const isControlled   = controlledOpen !== undefined;
  const [internalOpen, setInternalOpen] = useState(false);
  const [leaving,      setLeaving]      = useState(false);
  const [mounted,      setMounted]      = useState(false);
  const [position,     setPosition]     = useState({ top: 0, left: 0 });

  const open        = isControlled ? controlledOpen : internalOpen;
  const triggerRef  = useRef<HTMLElement>(null);
  const popoverRef  = useRef<HTMLDivElement>(null);
  const leaveTimer  = useRef<ReturnType<typeof setTimeout> | null>(null);
  const popoverId   = useId();

  const { side, align } = parsePlacement(placement);

  const setOpen = useCallback((next: boolean) => {
    if (!isControlled) setInternalOpen(next);
    onOpenChange?.(next);
  }, [isControlled, onOpenChange]);

  const toggle = useCallback(() => setOpen(!open), [open, setOpen]);

  const close = useCallback(() => {
    setLeaving(true);
    leaveTimer.current = setTimeout(() => {
      setLeaving(false);
      setMounted(false);
      setOpen(false);
    }, ANIM_OUT_MS);
  }, [setOpen]);

  // open → mount
  useEffect(() => {
    if (open) {
      if (leaveTimer.current) { clearTimeout(leaveTimer.current); leaveTimer.current = null; }
      setLeaving(false);
      setMounted(true);
    } else if (mounted && !leaving) {
      close();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // position after mount — needs popover dimensions so we read them after render
  useEffect(() => {
    if (!mounted || !triggerRef.current || !popoverRef.current) return;
    const tRect = triggerRef.current.getBoundingClientRect();
    const pRect = popoverRef.current.getBoundingClientRect();
    const pos   = computePosition(tRect, pRect, side, align, window.scrollX, window.scrollY);
    setPosition(pos);
  }, [mounted, side, align]);

  // close on outside click
  useEffect(() => {
    if (!mounted || !closeOnOutside) return;
    const handler = (e: MouseEvent) => {
      if (
        popoverRef.current && !popoverRef.current.contains(e.target as Node) &&
        triggerRef.current && !triggerRef.current.contains(e.target as Node)
      ) close();
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [mounted, closeOnOutside, close]);

  // close on Escape
  useEffect(() => {
    if (!mounted) return;
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") close(); };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [mounted, close]);

  const triggerEl = React.cloneElement(trigger, {
    ref: triggerRef,
    onClick: (e: React.MouseEvent) => { toggle(); trigger.props.onClick?.(e); },
    "aria-expanded": open,
    "aria-controls": popoverId,
    "aria-haspopup": "dialog" as const,
  });

  return (
    <>
      {triggerEl}
      {mounted &&
        ReactDOM.createPortal(
          <div
            ref={popoverRef}
            id={popoverId}
            role="dialog"
            aria-modal="false"
            className={cn(
              "vyre-popover",
              `vyre-popover--${side}`,
              leaving && "vyre-popover--leaving",
              className
            )}
            style={{ top: position.top, left: position.left }}
          >
            {children}
          </div>,
          document.body
        )}
    </>
  );
};

Popover.displayName = "VyrePopover";

// packages/vue/src/components/Popover/Popover.vue
<script setup lang="ts">
/**
 * @usevyre/vue — Popover
 *
 * AI CONTEXT:
 * ┌─────────────────────────────────────────────────────────┐
 * │ Component:  Popover                                     │
 * │ Import:     import { Popover } from "@usevyre/vue"         │
 * │                                                         │
 * │ Props:                                                  │
 * │   placement      = "bottom"(default)                    │
 * │                    "top"|"top-start"|"top-end"          │
 * │                    "bottom"|"bottom-start"|"bottom-end" │
 * │                    "left"|"left-start"|"left-end"       │
 * │                    "right"|"right-start"|"right-end"    │
 * │   closeOnOutside = boolean (default: true)              │
 * │                                                         │
 * │ Slots:                                                  │
 * │   trigger — the anchor element (required)               │
 * │   default — popover content                             │
 * │                                                         │
 * │ Model:                                                  │
 * │   v-model (boolean) — open state                        │
 * └─────────────────────────────────────────────────────────┘
 *
 * @example
 * <Popover v-model="open" placement="bottom-start">
 *   <template #trigger>
 *     <Button variant="ghost">Open</Button>
 *   </template>
 *   <p>Popover content here.</p>
 * </Popover>
 */

import { ref, watch, nextTick, onBeforeUnmount, computed, Teleport, Transition } from "vue";
import { cn } from "../../utils/cn";

type PopoverSide      = "top" | "bottom" | "left" | "right";
type PopoverAlign     = "start" | "center" | "end";
type PopoverPlacement =
  | "top" | "top-start" | "top-end"
  | "bottom" | "bottom-start" | "bottom-end"
  | "left" | "left-start" | "left-end"
  | "right" | "right-start" | "right-end";

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    placement?: PopoverPlacement;
    closeOnOutside?: boolean;
    class?: string;
  }>(),
  { modelValue: false, placement: "bottom", closeOnOutside: true }
);

const emit = defineEmits<{
  (e: "update:modelValue", val: boolean): void;
}>();

const triggerRef = ref<HTMLElement | null>(null);
const popoverRef = ref<HTMLDivElement | null>(null);
const position   = ref({ top: 0, left: 0 });
const visible    = ref(props.modelValue);

const GAP = 8;

function parsePlacement(p: PopoverPlacement): { side: PopoverSide; align: PopoverAlign } {
  const [side, align] = p.split("-") as [PopoverSide, PopoverAlign | undefined];
  return { side, align: align ?? "center" };
}

function computePosition() {
  const triggerEl  = triggerRef.value;
  const popoverEl  = popoverRef.value;
  if (!triggerEl || !popoverEl) return;

  const tRect   = triggerEl.getBoundingClientRect();
  const pRect   = popoverEl.getBoundingClientRect();
  const scrollX = window.scrollX;
  const scrollY = window.scrollY;
  const { side, align } = parsePlacement(props.placement);

  const tw = tRect.width;
  const th = tRect.height;
  const pw = pRect.width;
  const ph = pRect.height;
  const tx = tRect.left + scrollX;
  const ty = tRect.top  + scrollY;

  let top = 0, left = 0;

  switch (side) {
    case "top":    top  = ty - ph - GAP; break;
    case "bottom": top  = ty + th + GAP; break;
    case "left":   left = tx - pw - GAP; break;
    case "right":  left = tx + tw + GAP; break;
  }

  if (side === "top" || side === "bottom") {
    switch (align) {
      case "start":  left = tx;                    break;
      case "center": left = tx + tw / 2 - pw / 2; break;
      case "end":    left = tx + tw - pw;           break;
    }
  } else {
    switch (align) {
      case "start":  top = ty;                    break;
      case "center": top = ty + th / 2 - ph / 2; break;
      case "end":    top = ty + th - ph;           break;
    }
  }

  position.value = { top, left };
}

watch(() => props.modelValue, (val) => { visible.value = val; });
watch(visible, async (val) => {
  emit("update:modelValue", val);
  if (val) {
    await nextTick();
    computePosition();
  }
});

function toggle() { visible.value = !visible.value; }

function handleOutside(e: MouseEvent) {
  if (!props.closeOnOutside) return;
  const target = e.target as Node;
  if (popoverRef.value?.contains(target)) return;
  if (triggerRef.value?.contains(target)) return;
  visible.value = false;
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Escape") visible.value = false;
}

watch(visible, (val) => {
  if (val) {
    document.addEventListener("mousedown", handleOutside);
    document.addEventListener("keydown",   handleKeydown);
  } else {
    document.removeEventListener("mousedown", handleOutside);
    document.removeEventListener("keydown",   handleKeydown);
  }
});

onBeforeUnmount(() => {
  document.removeEventListener("mousedown", handleOutside);
  document.removeEventListener("keydown",   handleKeydown);
});

const side = computed(() => parsePlacement(props.placement).side);
const popoverClasses = computed(() =>
  cn("vyre-popover", `vyre-popover--${side.value}`, props.class)
);
</script>

<template>
  <span style="display: contents">
    <span ref="triggerRef" style="display: contents" @click="toggle">
      <slot name="trigger" />
    </span>
    <Teleport to="body">
      <Transition name="vyre-popover-fade">
        <div
          v-if="visible"
          ref="popoverRef"
          role="dialog"
          aria-modal="false"
          :class="popoverClasses"
          :style="{ position: 'absolute', top: `${position.top}px`, left: `${position.left}px` }"
        >
          <slot />
        </div>
      </Transition>
    </Teleport>
  </span>
</template>

<style scoped>
.vyre-popover-fade-enter-active,
.vyre-popover-fade-leave-active {
  transition: opacity var(--vyre-transition-duration-fast, 120ms) ease,
              transform var(--vyre-transition-duration-fast, 120ms) ease;
}
.vyre-popover-fade-enter-from,
.vyre-popover-fade-leave-to  { opacity: 0; transform: scale(0.95); }
.vyre-popover-fade-enter-to,
.vyre-popover-fade-leave-from { opacity: 1; transform: scale(1); }
</style>
